jobs:
  build:
    docker:
      - image: circleci/node:16.15.0
    steps:
      - checkout
      - run: npm i
      - run: npm run lint

  test:
    docker:
      - image: circleci/node:16.15.0
    steps:
      - checkout
      - run: npm i
      - run: npm run test

  analyze:
    docker:
      - image: circleci/node:16.15.0
    steps:
      - checkout
      - run: npm audit

workflows:
  jobs:
    - build
    - test:
        requires:
          - build
    - analyze:
        requires:
          - test
